### ISSUE TITLE
removed from comments

### ISSUE THREAD

**Issue by Paliha** [ThunderCls/xAnalyzer#10]
Hi !
Why use the analysis field reviews - DbgSetCommentAt ?
Very inconvenient to search and sort your notes.
There are also other types of data:
DbgSetAutoCommentAt 
DbgSetAutoLabelAt
Otherwise, thanks, missed the structuring of call system functions...)))

**Comment by ThunderCls** [comment]
Hey !
I know what you mean, but still, Auto Labels are also listed by x64dbg view/labels so that would do it just more of the same and as for Auto Comments...well, they are already used for function arguments, so I wanted to have a different color/type of element to represent the function names and that could also be listed, since you won´t get any "sub_[EAX]", for instance, in the intermodular calls list. Anyways, if you feel this is too annoying, you can fork/change it to meet your needs, you would only have to change the line:

DbgSetCommentAt(inst->Address, CommentString);

in the SetAutoCommentIfCommentIsEmpty function to DbgSetAutoCommentAt/DbgSetAutoLabelAt and that would do it ;)
you're welcome
