### ISSUE TITLE
Incorrect parameter detection

### ISSUE THREAD

**Issue by justanotheranonymoususer** [ThunderCls/xAnalyzer#17]
See the screenshot below. The arguments are detected for `sub_1400091C0`, even though the call of `CoInitializeEx` invalidates the registers.

![image_137](https://cloud.githubusercontent.com/assets/5781692/23398423/299c2bc4-fda5-11e6-991b-f6b02f8ce7e4.png)

**Comment by ThunderCls** [comment]
Well, I've tried to replicate your code but it is working fine for me.

![image](https://cloud.githubusercontent.com/assets/13303069/23443958/37cfd73a-fe00-11e6-8d4e-1ba4209468f1.png)

If you continue getting this issues, could you please send me the executable in order to replicate exactly your case?

**Comment by justanotheranonymoususer** [comment]
Do you have the `Analyze Undefined Functions` option enabled? I forgot to mention that, sorry.

**Comment by ThunderCls** [comment]
Yup

![issue](https://cloud.githubusercontent.com/assets/13303069/23444509/9a1e7394-fe03-11e6-816c-1efd7fac951f.gif)

**Comment by justanotheranonymoususer** [comment]
[Here's the file](https://www.dropbox.com/s/gxhajves8il8b9v/test.exe?dl=1).

**Comment by ThunderCls** [comment]
Thanks to the file I could check the bug. Actually there´s no issues in the main code but in the definition files, apparently the parser failed in a couple of them. A fix will soon be pushed tho. Once again, thanks for reporting ;)
