### ISSUE TITLE
wrong parameter recognition

### ISSUE THREAD

**Issue by atar-axis** [ThunderCls/xAnalyzer#26]
I am not totally sure, but i guess that `MOV ...` is not one of the parameters - right? :D

![5duxcci](https://user-images.githubusercontent.com/11148588/36177646-b12715ce-1116-11e8-87ed-112676dc7baa.png)
https://i.imgur.com/5duxcci.png

**Comment by ThunderCls** [comment]
You're right 😀. 
How would you analyze and pick, in this case, which instructions (from 21E6 to 21F7) belong to the function call and which don't. How would you purge that and code it in a standard algorithm that could be applied to every other function call?

**Comment by atar-axis** [comment]
hum, good question :D i don't know enough about the x64/xAnalyzer internals to really answer that. how is it done at the moment?

I think you can never be absolutely sure about which arguments is part of the call and which is not, not before you are really there (at the call)... but *i* think that - until there is a better solution - you can simply ignore everything except `push`es - what do *you* think?

**Comment by ThunderCls** [comment]
* The internals of xAnalyzer are already there...it's an open source project xD. 
You can give a look at: "xanalyzer.cpp -> IsArgumentInstruction" function to find out how the plugin chooses which instructions are allowed and which don't. 
xAnalyzer then uses a stack to store the "valid" instructions and when a function call is found it'll take out the last instructions according to the amount of arguments the function has on the definition file. In this case of yours, the mov instruction is the first one in coming out of the stack as part of the valid arguments list instructions for this call. That's how the plugin basically handles the argument instructions for a function call.

* Your reasoning of selecting ONLY the "push" instructions was the initial scheme of xAnalyzer and, of course it would only be valid for x86 executables, since x64 can handle function arguments using mov, lea, xor, and....etc.

* As you stated before, depending on the compiler and how fancy it gets with its optimizations, the "mov" [esp*] or [ebp*] instruction could also be used for passing arguments to the function, making the plugin to fail in these scenarios. That's why xAnalyzer was updated in order to contemplate these specific "mov" cases as well. 

If only "push"es are allowed, the plugin is gonna fails on the mov scenarios and visceversa, so, until a workaround or a better algorithm to filter out/predict the "correct argument instructions" for both cases is found, the plugin is gonna be buggy regarding this feature. That's what I meant in my previous comment, it's not a trivial task.

The arguments line should be drawn correctly, are you using the last version of both, the plugin and x64dbg? If you are, could you upload that sample to give it a look?

**Comment by atar-axis** [comment]
Thank you for the insight!
I never debugged any x86_64 executable, therefore I had to look that up and... yes, for sure, you are right.

In my case it was/is an x86 executable - therefore the problem is somehow `IsMovStack()`. We maybe need something that checks if...
* in case of [ESP+n]: |n| is bigger than the argument count
* in case of [EBP+n]: ...
But yes, so easy to implement I guess.

Anyhow!
At least in the moment  of calling we know exactly which stack-portion is which argument.
So what do you think about a **show in argument widget** option?

Something that turns
```
1: [esp] 00000020 
2: [esp+4] 00000020 
3: [esp+8] 00000000 
4: [esp+C] 00000024 
5: [esp+10] 00000001 
```

into

```
1: [esp]    PVOID HeapHandle 00000020 
2: [esp+4]  ULONG Flags      00000020 
3: [esp+8]  PVOID HeapBase   00000000 
4: [esp+C]  00000024  <-- automatically removed since xAnalyzer could set the Argument Counter
5: [esp+10] 00000001 <-- automatically removed since xAnalyzer could set the Argument Counter
```

---

I uploaded the file you are asked for, but beware - it is ransomware! (pasword: malware).


[malware.zip](https://github.com/ThunderCls/xAnalyzer/files/1728078/malware.zip)

**Comment by ThunderCls** [comment]
OK I think you got something there to somehow workaround the mov issue at least for now

If(n / 4 <= function_argument_count)
    VALID ARGUMENT INSTRUCTION

In your code that "mov [ebp + 24]" would be out of the picture since the function only has 6 parameters and that +24 would be way off that. So yeah I think I can come up with some code by using this approach. I'll keep this issue updated once is done.

Regarding the arguments widget yeah, I'm all for implementing this in xAnalyzer, we just gotta work on some plugin interface on x64dbg to allow plugins to handle that info, I just haven't had time to implement it myself, anyways , if you're interested we could work that out.

**Comment by atar-axis** [comment]
> So yeah I think I can come up with some code by using this approach. I'll keep this issue updated once is done.

Nice! No hurry ;)

>  Regarding the arguments widget yeah, I'm all for implementing this in xAnalyzer ... if you're interested we could work that out

Yeah! I already talked to mrexodia about this some days before, he said it would be "minor time investment" and shouldn't be difficult. I'm relatively busy at the moment, too. Let's do that in some weeks - we should open an independent enhancement-issue in the meantime.

**Comment by ThunderCls** [comment]
Ok, now we have an issue here. Even when we can predict [ESP*] instructions, there's no way that I can find to choose the correct argument instructions using [EBP*]. High stack addresses correspond to the stack base pointer [EBP+n] and those refer to the actual function parameters. On the other hand [EBP-n] or low stack addresses correspond to local vars, which are most likely to be used as parameters for function calls inside the actual function. The thing is that anything from [EBP-n] to [EBP+n] could be used as a function parameter and there's no reliable way (at least that I can find) to predict statically which of all is gona be used as an actual parameter in a function call. I could just ban every [EBP*] instruction...I'm out of ideas.

**Comment by atar-axis** [comment]
Hum, tell me if I am wrong, but...
When a function is called, a new stack frame is created at the adress where ESP is pointing at. So EBP after calling is the same as ESP was before calling.

Therefore it makes sense `mov` **to** `[ESP+n]` before calling instead of `push`ing the argument. This is e.g discussed here: https://stackoverflow.com/questions/39232880/using-push-or-mov-to-pass-arguments-to-a-function

But... why should I `mov` sth **to** `[EBP+n]` in order to pass an argument to a stdcall function?!

**Comment by ThunderCls** [comment]
I don't think we're in the same page here.
EBP indeed points to the previous frame's base pointer (like a backup pointer of ESP before going into a function). It is used as a base pointer so parameters and local vars of the current function you're in are accessed by referring to [EBP+n] or [EBP-n] accordingly. Take this for instance.

![image](https://user-images.githubusercontent.com/13303069/36400675-707193a4-15a0-11e8-9c08-1ce624451277.png)

Having said that, EBP is usefull when doing dynamic analysis of function calls, stack trace, etc...the thing is that when you're doing static analysis and you try to predict parameters for a function call you can't reliable use ebp. In addition to that, I haven't even seen yet a code that uses EBP as a function call argument instruction. Have you? Don't know if I explained myself ok.

**Comment by atar-axis** [comment]
perfect - I think now we are in tune ;) Thanks!
