### ISSUE TITLE
dont know why,it didnt work on my PC

### ISSUE THREAD

**Issue by Zayia** [ThunderCls/xAnalyzer#29]
x64dbg version:snapshot_2018-04-05_00-33.zip
xAnalyzer version: 2.5.0
cant find it in the "Plugins" menu and in the secondary menu in the Disasm window

**Comment by ThunderCls** [comment]
Can you post the content of your x64dbg log window right after you start it?

**Comment by Zayia** [comment]
`Initializing wait objects...
Initializing debugger...
Initializing debugger functions...
Setting JSON memory management functions...
Initializing capstone...
Initializing Yara...
Getting directory information...
Start file read thread...
Symbol Path: C:\debuger\吾爱破解工具包\Tools\Debuggers\x64dbg\x32\symbols
Allocating message stack...
Initializing global script variables...
Registering debugger commands...
Registering GUI command handler...
Registering expression functions...
Registering format functions...
Registering Script DLL command handler...
Starting command loop...
Initialization successful!
Loading plugins...
[PLUGIN] Api Break v5 Loaded!
[PLUGIN] x64dbg_tol v1 Loaded!
Error codes database loaded!
Exception codes database loaded!
NTSTATUS codes database loaded!
Windows constant database loaded!
Reading notes file...
File read thread finished!
[xAnalyzer] Failed to locate API definitions files. 
            Check that the folder: C:\debuger\�ᰮ�ƽ⹤�߰�\Tools\Debuggers\x64dbg\x32\plugins\apis_def\ 
            and definition files are present and try again...exiting plugin initialization! 
[PLUGIN] pluginit failed for plugin: xAnalyzer.dp32
Handling command line...
  "C:\debuger\吾爱破解工具包\Tools\Debuggers\x64dbg\x32\x32dbg.exe" 
`

**Comment by Zayia** [comment]
work now
download the apis_def.zip and unzip it in the folder and its work now
thx for the amazing plugin

**Comment by Retr0x01** [comment]
Hello,

It doesn't work for me even though I unzipped the file and placed it in the correct location. Still, the plugin doesn't show up.

I installed this debugger using ReToolKit, and it already came with some plugins pre-installed. So logically, when I add this file, it should appear, but it doesn't.

**Comment by mrfearless** [comment]
Download the files from the releases: **apis_def.zip**, **xAnalyzer.dp32** and **xAnalyzer.dp64**. 


Right click on each file downloaded, and make sure to tick the "_This file came from another computer and might be blocked to help protect this computer_" checkbox called **Unblock**. Click OK.

- Copy **xAnalyzer.dp32** to the `X:\x64dbg\x32\plugins\` folder (or wherever x64dbg (x86 32bit) is installed: x64dbg\x32\plugins\)
- Copy **xAnalyzer.dp64** to the `X:\x64dbg\x64\plugins\` folder (or wherever x64dbg (x64 64bit) is installed: x64dbg\x64\plugins\)
- Unzip **apis_def.zip** in the plugins folder of **each** version so that it looks like: `X:\x64dbg\x32\plugins\apis_def\` and `X:\x64dbg\x64\plugins\apis_def\`  with the api definition files located in each folder. Note: there is also a `headers` folder under the `apis_def` folder.

Start x64dbg, check logs to verify if xAnalyzer is loaded.
