### ISSUE TITLE
Extended analysis is always done, even though option is not enabled.

### ISSUE THREAD

**Issue by strongbox1000** [ThunderCls/xAnalyzer#38]
When option automatic analysis is enabled, x32dbg always does an **extended** analysis even though extended option is **not** enabled. Running latest version of x64dbg and xAnalyzer. Have the same issue in x64dbg. If I turn off automatic analysis, no analysis is done.

![menu](https://user-images.githubusercontent.com/44455341/47474456-9ce79600-d7dc-11e8-9663-6d764f9d9d43.jpg)

![capture](https://user-images.githubusercontent.com/44455341/47474461-a07b1d00-d7dc-11e8-9c8d-4c2d7ef45da1.JPG)

**Comment by ThunderCls** [comment]
Yeah well, I guess it could be a missused term calling "Extended Analysis" to that menu entry. With "Extended Analysis" it all comes down to the amount of code that will be analyzed. If "Extended Analysis" is selected xAnalyzer it's gonna work over the entire code section, whereas if it's not selected it will only start at the EP of the executable. Because of with some compilers (borland, etc) and some specific cases you may have important code before the EP, that's why the "Extended Analysis" was introduced, to allow more code to be analyzed. So yeah, it's not a bug...thanks tho
