### ISSUE TITLE
Cannot run the Plugins Can't be in xAnalyzer.dp32 or xAnalyzer.dp64 Locate TianGetProcessInfomation on

### ISSUE THREAD

**Issue by CNLouisLiu** [ThunderCls/xAnalyzer#48]
![image](https://user-images.githubusercontent.com/35774374/93263422-56d4ba80-f7d8-11ea-857d-33e0b481a960.png)

**Comment by CNLouisLiu** [comment]
The same error occurs for APIInfo

**Comment by ThunderCls** [comment]
That error is due to a dual debugger engine (Titan Engine/Gleebug) recently implemented in x64dbg. You should switch back to Titan Engine in order to use the plugin again. For more information on how to do it you can open an issue at: 

https://github.com/x64dbg/x64dbg/issues/new/choose

or you can also drop your question on the x64dbg telegram and/or discord channels
